package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            password("env.CONFIGURATION", "", label = "Properties", description = """Valid Syntax: Key="value" pairs, one pair per line. Maximum number of allowed characters are 4K""", display = ParameterDisplay.PROMPT)
        }
        update {
            password("env.CONFIGURATION", "credentialsJSON:313af02f-06ea-4894-bb6f-cfe5c023af5e", label = "Properties", description = """Valid Syntax: Key="value" pairs, one pair per line. Maximum number of allowed characters are 4K""", display = ParameterDisplay.PROMPT)
        }
        add {
            checkbox("env.TESt", "", label = "Dry Run", description = "execute all steps except update", display = ParameterDisplay.PROMPT,
                      checked = "true", unchecked = "false")
        }
    }
}
